name: heartinfo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  flutter_speed_dial: ^1.0.9
  flutter_map:
  http: ^0.12.0
  url_launcher: ^3.0.0
  flutter_html: ^0.8.2
  marquee_flutter: ^0.1.1
  flutter_html_view: ^0.5.10
  carousel_slider: ^1.0.1
  shimmer:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.0+2
  dio: any
  path_provider: any
  shared_preferences: "^0.4.2"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  image_path: "images/ic_launcher.png"
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/header.jpg
    - images/programmes.png
    - images/banner3.png
    - images/fotter.png
    - images/hlogo1.png
    - images/powered_by1.png
    - images/applied.png
    - images/imag.png
    - images/searh.png
    - images/globe.png
    - images/customer.png
    - images/heart1.png
    - images/settings.png
    - images/cap.png
    - images/caps.png
    - images/intramap.png
    - images/insta.png
    - images/job.png
    - images/fjob.png
    - images/fb1.png
    - images/vtdi.png
    - images/ndarlogo.png
    - images/vtdilogo.png
    - images/hopelogo.png
    - images/jflllogo.png
    - images/jobs.jpg
    - images/study.png
    - images/loginpage.jpeg
    - images/whatsapp.png
    - images/twitter.png
    - images/training.png
    - local_json/offerings/heart.json
    - local_json/offerings/vtdi.json
    - local_json/offerings/youth.json
    - local_json/offerings/adult.json
    - local_json/jobs/jobs.json
    - local_json/contacts/contact.json
    - images/p.png
    - images/promo1.jpg
    - images/promo2.jpg
    - images/promo3.jpg
    - images/promo4.jpg
    - images/jobsearch.png
    - images/ic_launcher-web.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
